# Dependencies
markdown:         kramdown
highlighter:	  pygments

# Permalinks
permalink:        pretty

# Setup
title:            Subliminal Undertones
tagline:          Just because
description:      Bringing to focus
url:              http://dpundir.com
baseurl:          /

author:
  name:           Dinkar Pundir
  url:            https://twitter.com/dinkarpundir

paginate:         5

# Custom vars
github:
  repo:           https://github.com/dinkar
twitter_username: dinkarpundir
facebook_username: dinkar.pundir
email: dinkar@dpundir.com
